language: node_js

matrix:
  include:
    - node_js: '11'
    - node_js: 'lts/*'
      env: UPLOAD_COVERALLS=yes

env:
  global:
    - BUILD_ENV=production

notifications:
  email: false

script:
  - env
  - NODE_ENV=$BUILD_ENV yarn lint
  - NODE_ENV=$BUILD_ENV yarn test --coverage --coverageReporters lcov --runInBand

after_success:
  - test $UPLOAD_COVERALLS = 'yes' && test $TRAVIS_EVENT_TYPE = 'push' && test $TRAVIS_BRANCH = 'master' && yarn coveralls < coverage/lcov.info
