language: node_js
node_js:
  - '11.10'
  - 'lts/*'

env:
  - BUILD_ENV=production

notifications:
  email: false

script:
  - NODE_ENV=$BUILD_ENV yarn lint
  - NODE_ENV=$BUILD_ENV yarn test --coverage --coverageReporters lcov --runInBand

after_success:
  - yarn coveralls < coverage/lcov.info
